@BASE_MEDIA_URL = http://localhost:3000/api/v1/media
@INTERNAL_SECRET = superinternalsecret

###

PUT {{BASE_MEDIA_URL}}
x-internal-secret: {{INTERNAL_SECRET}}
Cookie: session_id=019e0d50-6e7f-7000-8a25-ccefdc6fc80b.WSU2FcripewG%2BZzS1Ce0rmQi8jb1mELiJSfDcNU%2FjOY%3D;
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="altText"

Ini figur marisa
--boundary
Content-Disposition: form-data; name="isPublic"

true
--boundary
Content-Disposition: form-data; name="file"; filename="marisa.jpg"
Content-Type: image/jpg

< ./files/marisa.jpg
--boundary--

###

PUT {{BASE_MEDIA_URL}}
x-internal-secret: {{INTERNAL_SECRET}}
Cookie: session_id=019e0d50-6e7f-7000-8a25-ccefdc6fc80b.WSU2FcripewG%2BZzS1Ce0rmQi8jb1mELiJSfDcNU%2FjOY%3D;
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="altText"

Ini mokou & kaguya
--boundary
Content-Disposition: form-data; name="isPublic"

true
--boundary
Content-Disposition: form-data; name="file"; filename="marisa.jpg"
Content-Type: image/jpg

< ./files/mokoukaguya.jpg
--boundary--

###

GET {{BASE_MEDIA_URL}}/all-data
x-internal-secret: {{INTERNAL_SECRET}}

###

DELETE {{BASE_MEDIA_URL}}
x-internal-secret: {{INTERNAL_SECRET}}