@BASE_MEDIA_URL = http://localhost:3000/api/v1/media
@INTERNAL_SECRET = superinternalsecret
@COOKIE = session_id=019e1035-fd8b-7000-afce-c8f40e2fd46c.nupgPIEkUpuP9UsRjV0eGzlKcX3WaYS9z3fcXK8iIFQ%3D;

###

PUT {{BASE_MEDIA_URL}}
x-internal-secret: {{INTERNAL_SECRET}}
Cookie: {{COOKIE}}
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="altText"

Ini figur marisa
--boundary
Content-Disposition: form-data; name="isPublic"

true
--boundary
Content-Disposition: form-data; name="file"; filename="marisa.jpg"
Content-Type: image/jpg

< ../../files/marisa.jpg
--boundary--

###

PUT {{BASE_MEDIA_URL}}
x-internal-secret: {{INTERNAL_SECRET}}
Cookie: {{COOKIE}}
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="altText"

Ini mokou & kaguya
--boundary
Content-Disposition: form-data; name="isPublic"

true
--boundary
Content-Disposition: form-data; name="file"; filename="mokoukaguya.jpg"
Content-Type: image/jpg

< ../../files/mokoukaguya.jpg
--boundary--

###

GET {{BASE_MEDIA_URL}}/all-data
x-internal-secret: {{INTERNAL_SECRET}}

###

DELETE {{BASE_MEDIA_URL}}
x-internal-secret: {{INTERNAL_SECRET}}