services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: tahuisi-backend:${IMAGE_TAG}
    container_name: tahuisi-backend
    ports:
      - "3000:3000"
    environment:
      - COOKIE_SECRET=${COOKIE_SECRET}
      - INTERNAL_SECRET=${INTERNAL_SECRET}
      - NODE_ENV=production