@BASE_URL = http://localhost:3000/api/v1
@INTERNAL_SECRET = verysecretinternalsecretandsafe

@RYHUN_ID = 019de820-9665-7000-b03e-cc1235b4fcd4
@RYHUN_2_ID = 019de820-b0f5-7000-b8ab-ba7895b4b1df

// Auth routes
###

POST {{BASE_URL}}/auth/register
Content-Type: application/json

{
    "email": "ryhundua@emailbagus.com",
    "username": "ryhundua",
    "gender": "male",
    "displayName": "ryhun exists",
    "password": "verysecretpassword"
}

###

POST {{BASE_URL}}/auth/register
Content-Type: application/json

{
    "email": "ryhun@emailkeren.com",
    "username": "ryhun",
    "gender": "male",
    "displayName": "ryhun was here",
    "password": "verysecretpassword"
}

###

POST {{BASE_URL}}/auth/login
Content-Type: application/json

{
    "email": "ryhundua@emailbagus.com",
    "password": "verysecretpassword"
}

###

POST {{BASE_URL}}/auth/logout
Cookie: session_id=019de792-f396-7000-a065-144afddecd7a.43dAIuhiSO1UphTzberBsEJk%2F5cRt95P6XSPzB7I%2Bl8%3D;

###

GET {{BASE_URL}}/auth/sessions

###

DELETE {{BASE_URL}}/auth/sessions


// Article routes
###

GET {{BASE_URL}}/article/headlines
x-internal-secret: {{INTERNAL_SECRET}}

###

POST {{BASE_URL}}/article
x-internal-secret: {{INTERNAL_SECRET}}
Content-Type: application/json

{
    "article": {
        "slug": "artikel-1",
        "title": "Ini Adalah Judul pertama",
        "excerpt": "Sebuah artikel pertama",
        "status": "PUBLISHED",
        "thumbnailId": "019de45f-6989-71d8-a341-084523e6e50e",
        "isLive": true,
        "body": "ini isi artikel yang nantinya akan sangat panjang sekali gak tau apalah itu"
    },
    "authorIds": 
    [
        "019de817-e6ff-7000-9a1e-7a98db4182af"
    ]
}

###

POST {{BASE_URL}}/article
x-internal-secret: {{INTERNAL_SECRET}}
Content-Type: application/json

{
    "article": {
        "slug": "artikel-2",
        "title": "Artikel dengan multi author",
        "excerpt": "Sebuah artikel pertama",
        "status": "PUBLISHED",
        "thumbnailId": "019de45f-6989-71d8-a341-084523e6e50e",
        "isLive": true,
        "body": "ini isi artikel yang nantinya akan sangat panjang sekali gak tau apalah itu"
    },
    "authorIds": 
    [
        "019de817-e6ff-7000-9a1e-7a98db4182af",
        "019de81b-5d00-7000-9f20-a7a8f09ec53a"
    ]
}

###

GET {{BASE_URL}}/article/artikel-1
x-internal-secret: {{INTERNAL_SECRET}}

###

GET {{BASE_URL}}/article/artikel-2
x-internal-secret: {{INTERNAL_SECRET}}

###

DELETE {{BASE_URL}}/article/delete-all
x-internal-secret: {{INTERNAL_SECRET}}

###
