@BASE_URL = http://localhost:3000/api/v1

GET {{BASE_URL}}

###

POST {{BASE_URL}}/auth/register
Content-Type: application/json

{
    "email": "ryhun@emailkeren.com",
    "username": "ryhun",
    "gender": "male",
    "displayName": "ryhun was here",
    "password": "verysecretpassword"
}

###

POST {{BASE_URL}}/auth/login
Content-Type: application/json

{
    "email": "ryhun@emailkeren.com",
    "password": "verysecretpassword"
}

###

POST {{BASE_URL}}/auth/logout
Cookie: 019de1dc-ce94-7000-9698-36ae6429a899.0ZL1dLEwTZNIeGK43YhDRB6zVC8qFuH42R40ZbOkMhk%3D;

###

GET {{BASE_URL}}/auth/sessions

###

DELETE {{BASE_URL}}/auth/sessions